---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Install package htop | tcpdump | tshark 
  apt:
    name: 
        - htop
        - tcpdump
        - tshark
    state: latest
    
 - name: Ensure the installed service is started
   service:
    name:
        - htop
        - tcpdump
        - tshark
    state: started
    enabled: yes
